var quotes = [
    "Plan and carry out a scavenger hunt or treasure hunt.",
    "Take a hike.",
    "Go surfing!",
    "Play a board game.",
    "Have a spa night.",
    "Enjoy a candlelight dinner together at your home together. Dress up!",
    "Go for a bike ride",
    "Go bowling together. (Feeling light-hearted? Try “bowling with a twist” --between the legs, on one leg, left-handed, etc.)",
    "Head to an art gallery!",
    "Attend a local festival together.",
    "Find somewhere you can feed the ducks together (Feed birdseed or grapes instead of bread).",
    "Finger paint together",
    "Draw each other",
    "Head to the theatre!",
    "Prepare a completely new meal for you both, something you've never tried before!",
    "LUNA PARK!",
    "Play Mario Kart",
    "Go to the Zoo!",
    "Go to the Movies!",
    "Build a kite!",
    "Go iceskating!",
    "Go Karting!",
    "Go stargazing",
    "Visit a brewery for a tour!",
    "Divise a pub crawl and carry it out",
    "Head on a spontaneous picnic",
    "Head to a drive in cinema",
    "Head to the arcade and see who can get the highest score!",
    "Go Geocaching!",
    "Do a high-ropes course!",
    "Head to the library and pick books out for each other",
    "Visit a bookstore together and buy each other a book!",
    "Make popcorn and watch a movie at home",
    "Make pizza together",
    "Take a fancy car on a test drive (if they let us)",
    "Give each other massages",
    "Go mini-golfing",
    "Take a dance class together, something we don't already know yet!",
    "Play laser tag against each other",
    "Go to karaoke or play singstar",
    "Take a cooking class together",
    "Visit a botanical garden",
    "Play a game of pool at a local pub",
    "Attend a sports match",
    "Watch each other's favourite movies",
    "Learn a new skill from Youtube together",
    "Make cupcakes or a cake together",
    "Go rockclimbing together",
    "Go to the beach together",
    ]
    
    function getQuote() {
        var randomNumber = Math.floor(Math.random()* quotes.length)
        document.getElementById("newQuoteSection").innerHTML = quotes[randomNumber];
    }